# Generated by Django 3.1 on 2022-03-03 10:44

import agency.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_profile_type', models.CharField(choices=[('Public Company', 'Public Company'), ('Educational', 'Educational'), ('Self Employed', 'Self Employed'), ('Government Agency', 'Government Agency'), ('Non Profit', 'Non Profit'), ('Self Owned', 'Self Owned'), ('Privately Held', 'Privately Held'), ('Partnership', 'Partnership')], max_length=100, null=True)),
                ('agency_logo', models.ImageField(upload_to='', verbose_name='agency_logo_image')),
                ('agency_bg', models.ImageField(upload_to='', verbose_name='agency_bg_image')),
                ('domain_expertise', models.TextField()),
                ('speciality', models.TextField()),
                ('aboutus', models.TextField()),
                ('address', models.CharField(max_length=1500)),
                ('contact_email', models.CharField(max_length=500)),
                ('contact_no', models.CharField(max_length=10)),
                ('founded_year', models.CharField(max_length=5, null=True)),
                ('employee_count', models.CharField(choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1001-5000', '1001-5000 employees'), ('5001-10,000', '5001-10,000 employees'), ('10,001+', '10,001+ employees')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_freelancer', models.BooleanField(default=False)),
                ('is_agency', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AssignJobInternal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssociateJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSecureData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_request', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, max_length=200)),
                ('update_at', models.DateTimeField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAgencyConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=500, null=True)),
                ('workemail', models.EmailField(max_length=254)),
                ('client_name', models.CharField(max_length=500, null=True)),
                ('company_name', models.CharField(max_length=500, null=True)),
                ('contact_number', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=2000, null=True)),
                ('commission_rate', models.IntegerField()),
                ('contract_details', models.FileField(upload_to='', verbose_name='contract_details')),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_terminated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('system_generated', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DomainExpertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_logo', models.ImageField(upload_to='', verbose_name='FreelancerProfile_logo_image')),
                ('agency_bg', models.ImageField(upload_to='', verbose_name='FreelancerProfile_bg_image')),
                ('spaciality', models.TextField()),
                ('aboutus', models.TextField()),
                ('contact_no', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternalCandidateBasicDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_custom_id', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=100)),
                ('resume', models.FileField(max_length=500, null=True, upload_to=agency.models.resume_path_handler)),
                ('secure_resume', models.BooleanField(default=False)),
                ('secure_resume_file', models.FileField(max_length=500, null=True, upload_to=agency.models.resume_path_handler)),
                ('contact', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=100)),
                ('ctc', models.CharField(max_length=100, null=True)),
                ('expectedctc', models.CharField(max_length=100, null=True)),
                ('total_exper', models.CharField(max_length=100, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, max_length=200)),
                ('update_at', models.DateTimeField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternalCandidateNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InternalUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=11, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('total_experiance', models.CharField(default=0.0, max_length=100, null=True)),
                ('spaciility', models.TextField()),
                ('aboutus', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('system_generated', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_generated', models.BooleanField(default=False)),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RolePermissions_agency', to='agency.agency')),
            ],
        ),
    ]
