# Generated by Django 3.1 on 2022-03-04 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0003_auto_20220304_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField()),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_CandidateCategories', to='agency.agency')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_create_user_id_CandidateCategories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='internalcandidatebasicdetail',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='agency_add_internalcandidate_categories_id', to='agency.CandidateCategories'),
        ),
    ]
