# Generated by Django 3.1 on 2022-03-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_auto_20220304_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalcandidatebasicdetail',
            name='withdraw_by_Candidate',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
