# Generated by Django 3.1 on 2022-03-07 06:47

import agency.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_remove_candidate_job_apply_detail_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0005_internalcandidatebasicdetail_withdraw_by_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaluserprofile',
            name='unique_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CandidateTempDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('resume', models.FileField(max_length=500, null=True, upload_to=agency.models.resume_path_handler)),
                ('contact', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=100)),
                ('ctc', models.CharField(max_length=100, null=True)),
                ('expectedctc', models.CharField(max_length=100, null=True)),
                ('total_exper', models.CharField(max_length=100, null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='', verbose_name='candidate_pf_pic_temp_db_agency')),
                ('create_at', models.DateTimeField(auto_now_add=True, max_length=200)),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CandidateTempDatabase_agency', to='agency.agency')),
                ('ccandidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Candidateid_CandidateTempDatabase_agency', to=settings.AUTH_USER_MODEL)),
                ('current_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Candidatetempdatabase_current_city_agency', to='candidate.city')),
                ('notice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Candidatetempdatabase_notice_period_agency', to='candidate.noticeperiod')),
                ('prefered_city', models.ManyToManyField(null=True, related_name='Candidatetempdatabase_prefered_city_agency', to='candidate.City')),
                ('skills', models.ManyToManyField(null=True, related_name='Candidatetempdatabase_skill_id_agency', to='candidate.Skill')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CandidateTempDatabase_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
