# Generated by Django 3.1 on 2022-03-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_auto_20220307_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalcandidatebasicdetail',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='', verbose_name='candidate_pf_pic'),
        ),
    ]
