# Generated by Django 3.1 on 2022-03-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_internalcandidatebasicdetail_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesecuredata',
            name='update_at',
            field=models.DateTimeField(max_length=200, null=True),
        ),
    ]
