# Generated by Django 3.1 on 2022-03-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_auto_20220317_0726'),
    ]

    
