# Generated by Django 3.1 on 2022-03-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_auto_20220317_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyagencyconnection',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
