# Generated by Django 3.1 on 2022-03-25 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0005_stage_list_display_name'),
        ('agency', '0011_auto_20220317_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ_subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_MCQ_subject', to='agency.agency')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_agency_user_id_MCQ_subject', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mcq_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_description', models.TextField()),
                ('correct_option', models.CharField(max_length=1)),
                ('option_a', models.CharField(max_length=200, null=True)),
                ('option_b', models.CharField(max_length=200, null=True)),
                ('option_c', models.CharField(max_length=200, null=True)),
                ('option_d', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_mcq_Question', to='agency.agency')),
                ('mcq_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_subject_id', to='agency.mcq_subject')),
                ('question_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_mcq_question_level', to='candidate.questiondifficultylevel')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_agency_user_id_mcq_Question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
