# Generated by Django 3.1 on 2022-03-25 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_stage_list_display_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0012_mcq_question_mcq_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_ImageSubject', to='agency.agency')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_agency_user_id_ImageSubject', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_que_description', models.TextField()),
                ('question_file', models.FileField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_ImageQuestion', to='agency.agency')),
                ('question_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_image_question_level', to='candidate.questiondifficultylevel')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_Image_subject', to='agency.imagesubject')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_agency_user_id_ImageQuestion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(max_length=50)),
                ('option2', models.CharField(max_length=50)),
                ('option3', models.CharField(max_length=50)),
                ('option4', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
                ('file1', models.FileField(null=True, upload_to='')),
                ('file2', models.FileField(null=True, upload_to='')),
                ('file3', models.FileField(null=True, upload_to='')),
                ('file4', models.FileField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_ImageOption', to='agency.agency')),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_ImageQuestion_id', to='agency.imagequestion')),
                ('subject_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_ImageSubject_id', to='agency.imagesubject')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_agency_user_id_ImageOption', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
