# Generated by Django 3.1 on 2022-03-25 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_stage_list_display_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0016_audio_audio_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_Template', to='agency.agency')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_Template_stage', to='candidate.stage_list')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_agency_user_id_Template', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Template_creation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('active', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('created_by', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_Template_creation', to='agency.agency')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Template_creation_category_agency', to='agency.templatecategory')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Template_creation_agency_stage', to='candidate.stage_list')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_agency_id_Template_creation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreRequisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', tinymce.models.HTMLField()),
                ('html_data', tinymce.models.HTMLField()),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_PreRequisites', to='agency.agency')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_prerequisites_creation_category', to='agency.templatecategory')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_prerequisites_creation_stage', to='candidate.stage_list')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_prerequisites_creation_temnplate', to='agency.template_creation')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_agency_user_id_PreRequisites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
