# Generated by Django 3.1 on 2022-03-25 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0005_stage_list_display_name'),
        ('agency', '0017_prerequisites_template_creation_templatecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestionUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_mark', models.IntegerField(null=True)),
                ('question_time', models.CharField(max_length=5, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_exam_question_unit_question', to='agency.mcq_question')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_mcq_que_unit_temnplate', to='agency.template_creation')),
            ],
        ),
        migrations.CreateModel(
            name='ExamTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(max_length=6)),
                ('total_question', models.IntegerField()),
                ('basic_questions_count', models.IntegerField()),
                ('intermediate_questions_count', models.IntegerField()),
                ('advanced_questions_count', models.IntegerField()),
                ('allow_negative_marking', models.BooleanField(default=True)),
                ('marking_system', models.CharField(max_length=15, null=True)),
                ('basic_question_marks', models.IntegerField(null=True)),
                ('intermediate_question_marks', models.IntegerField(null=True)),
                ('advanced_question_marks', models.IntegerField(null=True)),
                ('question_wise_time', models.BooleanField(null=True)),
                ('duration', models.CharField(max_length=10, null=True)),
                ('negative_mark_percent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(max_length=200, null=True)),
                ('delete_at', models.DateTimeField(max_length=200, null=True)),
                ('advanced_questions', models.ManyToManyField(related_name='agency_id_exam_template_advanced_questions', to='agency.mcq_Question')),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_ExamTemplate', to='agency.agency')),
                ('basic_questions', models.ManyToManyField(related_name='agency_id_exam_template_basic_questions', to='agency.mcq_Question')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_mcq_creation_category', to='agency.templatecategory')),
                ('delete_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_delete_user_id_ExamTemplate', to=settings.AUTH_USER_MODEL)),
                ('intermediate_questions', models.ManyToManyField(related_name='agency_id_exam_template_intermediate_questions', to='agency.mcq_Question')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_mcq_creation_stage', to='candidate.stage_list')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_mcq_subject_temnplate', to='agency.mcq_subject')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_mcq_creation_temnplate', to='agency.template_creation')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_update_user_id_ExamTemplate', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_create_user_id_ExamTemplate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_QuestionPaper', to='agency.agency')),
                ('exam_question_units', models.ManyToManyField(related_name='agency_id_question_paper_exam_question_units', to='agency.ExamQuestionUnit')),
                ('exam_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_question_paper_exam_template', to='agency.examtemplate')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_create_user_id_QuestionPaper', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
