# Generated by Django 3.1 on 2022-03-25 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0005_stage_list_display_name'),
        ('agency', '0018_examquestionunit_examtemplate_questionpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageExamQuestionUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_mark', models.IntegerField(null=True)),
                ('question_time', models.CharField(max_length=5, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_Image_exam_question_unit_question', to='agency.imagequestion')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_Image_mcq_que_unit_temnplate', to='agency.template_creation')),
            ],
        ),
        migrations.CreateModel(
            name='ImageExamTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(max_length=6)),
                ('total_question', models.IntegerField()),
                ('basic_questions_count', models.IntegerField()),
                ('intermediate_questions_count', models.IntegerField()),
                ('advanced_questions_count', models.IntegerField()),
                ('allow_negative_marking', models.BooleanField(default=True)),
                ('marking_system', models.CharField(max_length=15, null=True)),
                ('basic_question_marks', models.IntegerField(null=True)),
                ('intermediate_question_marks', models.IntegerField(null=True)),
                ('advanced_question_marks', models.IntegerField(null=True)),
                ('question_wise_time', models.BooleanField(null=True)),
                ('duration', models.CharField(max_length=10, null=True)),
                ('negative_mark_percent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(max_length=200, null=True)),
                ('delete_at', models.DateTimeField(max_length=200, null=True)),
                ('advanced_questions', models.ManyToManyField(related_name='agency_Image_exam_template_advanced_questions', to='agency.ImageQuestion')),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_ImageExamTemplate', to='agency.agency')),
                ('basic_questions', models.ManyToManyField(related_name='agency_Image_exam_template_basic_questions', to='agency.ImageQuestion')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_Image_creation_category', to='agency.templatecategory')),
                ('delete_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_delete_user_id_ImageExamTemplate', to=settings.AUTH_USER_MODEL)),
                ('intermediate_questions', models.ManyToManyField(related_name='agency_Image_exam_template_intermediate_questions', to='agency.ImageQuestion')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_Image_creation_stage', to='candidate.stage_list')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_mcq_subject_temnplate', to='agency.imagesubject')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_Image_creation_temnplate', to='agency.template_creation')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_update_user_id_ImageExamTemplate', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_create_user_id_ImageExamTemplate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageQuestionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_ImageQuestionPaper', to='agency.agency')),
                ('exam_question_units', models.ManyToManyField(related_name='agency_Image_question_paper_exam_question_units', to='agency.ImageExamQuestionUnit')),
                ('exam_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_Image_question_paper_exam_template', to='agency.imageexamtemplate')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_create_user_id_ImageQuestionPaper', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
