# Generated by Django 3.1 on 2022-03-26 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0005_stage_list_display_name'),
        ('agency', '0019_imageexamquestionunit_imageexamtemplate_imagequestionpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptiveExamQuestionUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_mark', models.IntegerField(null=True)),
                ('question_time', models.CharField(max_length=5, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_Descriptive_exam_question_unit_question', to='agency.descriptive')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_Descriptive_que_unit_temnplate', to='agency.template_creation')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptiveExamTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('assignment_type', models.CharField(max_length=10, null=True)),
                ('total_question', models.IntegerField()),
                ('question_wise_time', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(max_length=200, null=True)),
                ('delete_at', models.DateTimeField(max_length=200, null=True)),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_DescriptiveExamTemplate', to='agency.agency')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_Descriptive_creation_category', to='agency.templatecategory')),
                ('delete_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_delete_user_id_DescriptiveExamTemplate', to=settings.AUTH_USER_MODEL)),
                ('descriptivequestions', models.ManyToManyField(related_name='agency_Descriptive_exam_template_questions', to='agency.Descriptive')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_Descriptive_creation_stage', to='candidate.stage_list')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_Descriptive_subject_temnplate', to='agency.descriptive_subject')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_Descriptive_creation_temnplate', to='agency.template_creation')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_update_user_id_DescriptiveExamTemplate', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_create_user_id_DescriptiveExamTemplate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DescriptiveQuestionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_DescriptiveQuestionPaper', to='agency.agency')),
                ('exam_question_units', models.ManyToManyField(related_name='agency_Descriptive_question_paper_exam_question_units', to='agency.DescriptiveExamQuestionUnit')),
                ('exam_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_Descriptive_question_paper_exam_template', to='agency.descriptiveexamtemplate')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_create_user_id_DescriptiveQuestionPaper', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
