# Generated by Django 3.1 on 2022-03-26 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_stage_list_display_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0020_descriptiveexamquestionunit_descriptiveexamtemplate_descriptivequestionpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioExamQuestionUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_mark', models.IntegerField(null=True)),
                ('question_time', models.CharField(max_length=5, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_Audio_exam_question_unit_question', to='agency.audio')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_Audio_que_unit_temnplate', to='agency.template_creation')),
            ],
        ),
        migrations.CreateModel(
            name='AudioExamTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(max_length=6)),
                ('total_question', models.IntegerField()),
                ('question_wise_time', models.BooleanField(default=True)),
                ('total_exam_time', models.CharField(max_length=9)),
                ('is_video', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(max_length=200, null=True)),
                ('delete_at', models.DateTimeField(max_length=200, null=True)),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_AudioExamTemplate', to='agency.agency')),
                ('audioquestions', models.ManyToManyField(related_name='agency_Audio_exam_template_questions', to='agency.Audio')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_Audio_creation_category', to='agency.templatecategory')),
                ('delete_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_delete_user_id_AudioExamTemplate', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_Audio_creation_stage', to='candidate.stage_list')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_Audio_subject_temnplate', to='agency.audio_subject')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_Audio_creation_temnplate', to='agency.template_creation')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_update_user_id_AudioExamTemplate', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_create_user_id_AudioExamTemplate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AudioQuestionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_AudioQuestionPaper', to='agency.agency')),
                ('exam_question_units', models.ManyToManyField(related_name='agency_Audio_question_paper_exam_question_units', to='agency.AudioExamQuestionUnit')),
                ('exam_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_Audio_question_paper_exam_template', to='agency.audioexamtemplate')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_create_user_id_AudioQuestionPaper', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
