# Generated by Django 3.1 on 2022-03-26 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0021_audioexamquestionunit_audioexamtemplate_audioquestionpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingExamConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('total_time', models.CharField(max_length=50)),
                ('total_question', models.CharField(max_length=50)),
                ('assignment_type', models.CharField(max_length=50)),
                ('exam_type', models.CharField(max_length=50)),
                ('technology', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(max_length=200, null=True)),
                ('delete_at', models.DateTimeField(max_length=200, null=True)),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_CodingExamConfiguration', to='agency.agency')),
                ('coding_category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_code_exam_config_category_id', to='agency.codingsubjectcategory')),
                ('coding_subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_exam_config_coding_subject_id', to='agency.codingsubject')),
                ('delete_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_delete_user_id_CodingExamConfiguration', to=settings.AUTH_USER_MODEL)),
                ('template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_coding_config_template', to='agency.template_creation')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_update_user_id_CodingExamConfiguration', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_create_user_id_CodingExamConfiguration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodingScoreCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('comment', models.TextField(null=True)),
                ('rating', models.CharField(max_length=10, null=True)),
                ('coding_exam_config_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_coding_configuration_rating', to='agency.codingexamconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='CodingExamQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(max_length=10, null=True)),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_CodingExamQuestions', to='agency.agency')),
                ('coding_exam_config_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cagency_oding_configuration_id', to='agency.codingexamconfiguration')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_coding_question_id', to='agency.codingquestion')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_create_user_id_CodingExamQuestions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
