# Generated by Django 3.1 on 2022-03-26 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_stage_list_display_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0024_customtemplate_customtemplatescorecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCreationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('target_date', models.DateField()),
                ('remote_job', models.BooleanField()),
                ('salary_as_per_market', models.BooleanField(default=False)),
                ('min_salary', models.CharField(max_length=10)),
                ('max_salary', models.CharField(max_length=10)),
                ('experience_year_min', models.CharField(max_length=10)),
                ('experience_year_max', models.CharField(max_length=10)),
                ('job_description', tinymce.models.HTMLField()),
                ('benefits', tinymce.models.HTMLField(max_length=100)),
                ('requirements', tinymce.models.HTMLField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('created_by', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(max_length=200, null=True)),
                ('delete_at', models.DateTimeField(max_length=200, null=True)),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_JobTemplate', to='agency.agency')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencyjob_creation_category', to='agency.templatecategory')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencyjob_template_city', to='candidate.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencyjob_template_country', to='candidate.country')),
                ('delete_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencydelete_user_id_JobCreationTemplate', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencyjob_template_department', to='agency.department')),
                ('industry_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencyjob_template_industry_type_id', to='candidate.industrytype')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencyjob_template_type_id', to='candidate.jobtypes')),
                ('jobshift', models.ManyToManyField(related_name='agencyjob_template_shift', to='candidate.JobShift')),
                ('required_skill', models.ManyToManyField(null=True, related_name='agencyjob_template_required_skill', to='candidate.Skill')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencyjob_creation_stage', to='candidate.stage_list')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencyjob_template_status_id', to='candidate.jobstatus')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencyjob_creation_temnplate', to='agency.template_creation')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencyupdate_user_id_JobCreationTemplates', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencycreate_user_id_JobTemplate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
