# Generated by Django 3.1 on 2022-03-28 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_stage_list_display_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0027_workflowconfiguration_workflows_workflowstages'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('target_date', models.DateField()),
                ('remote_job', models.BooleanField()),
                ('salary_as_per_market', models.BooleanField(default=False)),
                ('min_salary', models.CharField(max_length=10)),
                ('max_salary', models.CharField(max_length=10)),
                ('experience_year_min', models.CharField(max_length=10)),
                ('experience_year_max', models.CharField(max_length=10)),
                ('job_description', tinymce.models.HTMLField()),
                ('benefits', tinymce.models.HTMLField(max_length=100)),
                ('requirements', tinymce.models.HTMLField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('job_link', models.TextField(null=True)),
                ('is_publish', models.BooleanField(default=False)),
                ('publish_at', models.DateTimeField(null=True)),
                ('close_job_targetdate', models.BooleanField(default=False)),
                ('close_job', models.BooleanField(default=False)),
                ('close_job_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_company_id_JobCreation', to='agency.agency')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_job_city', to='candidate.city')),
                ('contact_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_contact_person_id', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_job_country', to='candidate.country')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_job_department_id', to='agency.department')),
                ('industry_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_industry_type_id', to='candidate.industrytype')),
                ('job_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_job_owner', to=settings.AUTH_USER_MODEL)),
                ('job_shift_id', models.ManyToManyField(null=True, related_name='agency_JobShift_job', to='candidate.JobShift')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_job_type_id', to='candidate.jobtypes')),
                ('required_skill', models.ManyToManyField(null=True, related_name='agency_required_skill_job', to='candidate.Skill')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_job_status_id', to='candidate.jobstatus')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_create_user_id_JobCreation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
