# Generated by Django 3.1 on 2022-03-28 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0005_stage_list_display_name'),
        ('agency', '0031_onthegostages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateJobStagesStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField()),
                ('assessment_done', models.BooleanField(default=False, null=True)),
                ('action_performed', models.BooleanField(default=False, null=True)),
                ('status', models.IntegerField(default=0)),
                ('reject_by_candidate', models.BooleanField(default=False, null=True)),
                ('custom_stage_name', models.CharField(max_length=100, null=True)),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_CandidateJobStagesStatus', to='agency.agency')),
                ('candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_candidate_workflow_stages_status', to=settings.AUTH_USER_MODEL)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_StagesStatus_job_workflow_id', to='agency.jobcreation')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_StagesStatus_workflow_stage', to='candidate.stage_list')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_workflow_template_stage_status', to='agency.template_creation')),
            ],
        ),
        migrations.CreateModel(
            name='AssociateCandidateInternal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_AssociateCandidateInternal', to='agency.agency')),
                ('candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_candidate_AssociateCandidateInternal_status', to=settings.AUTH_USER_MODEL)),
                ('internal_candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_companyinternal_candidate_AssociateJob_id', to='agency.internalcandidatebasicdetail')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_job_AssociateCandidateInternal_id', to='agency.jobcreation')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_create_user_id_AssociateCandidateInternal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppliedCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_type', models.CharField(max_length=100, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, max_length=200)),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_AppliedCandidate', to='agency.agency')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_applied_candidate_id', to=settings.AUTH_USER_MODEL)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_applied_job_id', to='agency.jobcreation')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_create_user_id_AppliedCandidate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
