# Generated by Django 3.1 on 2022-03-28 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_stage_list_display_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0032_appliedcandidate_associatecandidateinternal_candidatejobstagesstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentcompleted', models.BooleanField(default=False)),
                ('action_required', models.CharField(max_length=100, null=True)),
                ('reject', models.BooleanField(default=False)),
                ('withdraw', models.BooleanField(default=False)),
                ('hire', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, max_length=200)),
                ('update_at', models.DateTimeField(max_length=200, null=True)),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_Tracker', to='agency.agency')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_candidate_id_Tracker', to=settings.AUTH_USER_MODEL)),
                ('current_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_current_stage_Tracker', to='candidate.stage_list')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_job_id_Tracker', to='agency.jobcreation')),
                ('next_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_next_stage_Tracker', to='candidate.stage_list')),
            ],
        ),
    ]
