# Generated by Django 3.1 on 2022-03-30 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0033_tracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancerprofile',
            old_name='spaciality',
            new_name='speciality',
        ),
    ]
