# Generated by Django 3.1 on 2022-03-30 13:32

import agency.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0034_auto_20220330_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewScorecardResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('comment', models.TextField(null=True)),
                ('rating', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfferNegotiation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, null=True)),
                ('annual_ctc', models.TextField(null=True)),
                ('notice_period', models.CharField(max_length=100, null=True)),
                ('joining_date', models.DateField(null=True)),
                ('other_details', models.TextField(null=True)),
                ('from_company', models.BooleanField(null=True)),
                ('action_performed', models.BooleanField(default=False)),
                ('action_name', models.CharField(max_length=100, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='interviewscorecard',
            name='interview_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_template_id', to='agency.interviewtemplate'),
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.TextField(null=True)),
                ('bond', models.TextField(null=True)),
                ('NDA', models.TextField(null=True)),
                ('offer_letter', models.FileField(null=True, upload_to=agency.models.job_offer_path_handler)),
                ('is_accepted', models.BooleanField(default=False)),
                ('rejected_by_candidate', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, max_length=200)),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_JobOffer', to='agency.agency')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencycandidate_JobOffer', to=settings.AUTH_USER_MODEL)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencyJobOffer_job_id', to='agency.jobcreation')),
                ('job_stages_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencyJobOffer_job_stages_id', to='agency.candidatejobstagesstatus')),
                ('negotiations', models.ManyToManyField(related_name='agencyJobOffer_participants_ids', to='agency.OfferNegotiation')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencyJobOffer_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('meridiem', models.CharField(max_length=10, null=True)),
                ('interview_duration', models.CharField(max_length=100, null=True)),
                ('is_accepted', models.BooleanField(null=True)),
                ('interview_start_button_status', models.BooleanField(default=False, null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('reschedule_message', models.TextField(null=True)),
                ('interview_link', models.TextField(null=True, unique=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_InterviewSchedule', to='agency.agency')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencycandidate_InterviewSchedule', to=settings.AUTH_USER_MODEL)),
                ('interview_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencyinterview_template_obj', to='agency.interviewtemplate')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencyInterviewSchedule_job_id', to='agency.jobcreation')),
                ('job_stages_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencyInterviewSchedule_job_stages_id', to='agency.candidatejobstagesstatus')),
                ('participants', models.ManyToManyField(related_name='agencyInterviewSchedule_participants_ids', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencyInterviewSchedule_template_id', to='agency.template_creation')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencyInterviewSchedule_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_InterviewResult', to='agency.agency')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencycandidate_InterviewResult', to=settings.AUTH_USER_MODEL)),
                ('interview_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_InterviewResult', to='agency.interviewtemplate')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencyjob_id_InterviewResult', to='agency.jobcreation')),
                ('scorecard_results', models.ManyToManyField(null=True, related_name='agencyInterviewResult_scorecards', to='agency.InterviewScorecardResult')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencyInterviewResult_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateJobStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_withdraw', models.BooleanField(default=False)),
                ('is_hired', models.BooleanField(default=False)),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_JobStatus', to='agency.agency')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencycandidate_JobStatus', to=settings.AUTH_USER_MODEL)),
                ('hire_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencyuser_hired_JobStatus', to=settings.AUTH_USER_MODEL)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencyjob_id_JobStatus', to='agency.jobcreation')),
                ('withdraw_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencyuser_withdraw_JobStatus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
