# Generated by Django 3.1 on 2022-03-31 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0036_collaboration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomScorecardResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('comment', models.TextField(null=True)),
                ('rating', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_file_by_candidate', models.FileField(null=True, upload_to='')),
                ('description_by_candidate', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_id_CustomResult', to='agency.agency')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_candidate_CustomResult', to=settings.AUTH_USER_MODEL)),
                ('custom_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_CustomResult_template', to='agency.customtemplate')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_job_id_CustomResult', to='agency.jobcreation')),
                ('scorecard_results', models.ManyToManyField(null=True, related_name='agency_CustomResult_scorecards', to='agency.CustomScorecardResult')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_CustomResult_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
