# Generated by Django 3.1 on 2022-04-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0037_customresult_customscorecardresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='gender',
            field=models.CharField(default='male', max_length=10),
            preserve_default=False,
        ),
    ]
