# Generated by Django 3.1 on 2022-04-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0038_freelancerprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatejob',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
