# Generated by Django 3.1 on 2022-04-23 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0013_auto_20220423_0758'),
        ('agency', '0039_associatejob_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, max_length=200)),
                ('applied', models.BooleanField(default=False)),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_submission_AssociateJob_agency', to='agency.agency')),
                ('internal_candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_submissionJob_id', to='agency.internalcandidatebasicdetail')),
                ('internal_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_submissionuser', to='agency.internaluserprofile')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_submission_job_id', to='company.jobcreation')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_submissionAssociateJob_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
