# Generated by Django 3.1 on 2022-04-23 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20220423_0758'),
        ('agency', '0040_dailysubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysubmission',
            name='job_id',
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='agency_job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_daily_submission_job_id', to='agency.jobcreation'),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='company_job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_daily_submission_job_id', to='company.jobcreation'),
        ),
    ]
