# Generated by Django 3.1 on 2022-04-30 05:36

import agency.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0016_auto_20220409_1033'),
        ('agency', '0045_auto_20220429_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysubmission',
            name='candidate_custom_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='AppliedCandidateBasicDetails_categories_id', to='agency.CandidateCategories'),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='ctc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='current_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AppliedCandidateBasicDetails_current_city', to='candidate.city'),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='expectedctc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='notice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AppliedCandidateBasicDetails_applyjob_notice_period', to='candidate.noticeperiod'),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='prefered_city',
            field=models.ManyToManyField(null=True, related_name='AppliedCandidateBasicDetails_prefered_city', to='candidate.City'),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='', verbose_name='AppliedCandidateBasicDetails_pf_pic'),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='resume',
            field=models.FileField(max_length=500, null=True, upload_to=agency.models.resume_path_handler),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='secure_resume',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='secure_resume_file',
            field=models.FileField(max_length=500, null=True, upload_to=agency.models.resume_path_handler),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='skills',
            field=models.ManyToManyField(null=True, related_name='AppliedCandidateBasicDetails_skill_id', to='candidate.Skill'),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AppliedCandidateBasicDetails_source', to='candidate.source'),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='AppliedCandidateBasicDetails_tags_id', to='agency.Tags'),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='total_exper',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='update_at',
            field=models.DateTimeField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='varify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailysubmission',
            name='job_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
