# Generated by Django 3.1 on 2022-05-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0048_dailysubmission_candidate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysubmission',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='dailysubmission',
            name='tags',
        ),
    ]
