# Generated by Django 3.1 on 2022-03-03 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='randommcqexam',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_RandomMCQExam_exam', to='company.company'),
        ),
        migrations.AddField(
            model_name='randommcqexam',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_RandomMCQExam_exam_job_id', to='company.jobcreation'),
        ),
        migrations.AddField(
            model_name='randommcqexam',
            name='question',
            field=models.ManyToManyField(null=True, related_name='candidate_RandomMCQExam_question', to='company.mcq_Question'),
        ),
        migrations.AddField(
            model_name='randommcqexam',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_RandomMCQExam_exam_template_id', to='company.template_creation'),
        ),
        migrations.AddField(
            model_name='randomimageexam',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_RandomImageExam_exam', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='randomimageexam',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_RandomImageExam_exam', to='company.company'),
        ),
        migrations.AddField(
            model_name='randomimageexam',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_RandomImageExam_exam_job_id', to='company.jobcreation'),
        ),
        migrations.AddField(
            model_name='randomimageexam',
            name='question',
            field=models.ManyToManyField(null=True, related_name='candidate_RandomImageExam_question', to='company.ImageQuestion'),
        ),
        migrations.AddField(
            model_name='randomimageexam',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_RandomImageExam_exam_template_id', to='company.template_creation'),
        ),
        migrations.AddField(
            model_name='profile',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multiple_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prerequisitesfill',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_PreRequisites_ratio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prerequisitesfill',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_PreRequisites_company_jcr_id', to='company.company'),
        ),
        migrations.AddField(
            model_name='prerequisitesfill',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_PreRequisites_job_id', to='company.jobcreation'),
        ),
        migrations.AddField(
            model_name='prerequisitesfill',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_PreRequisites_template_id', to='company.template_creation'),
        ),
        migrations.AddField(
            model_name='permissions',
            name='permissionsmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PermissionsModel', to='candidate.permissionsmodel'),
        ),
        migrations.AddField(
            model_name='mcq_exam_result',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_mcq_exam_result', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mcq_exam_result',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_mcq_exam_result', to='company.company'),
        ),
        migrations.AddField(
            model_name='mcq_exam_result',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_mcq_exam_job_id_result', to='company.jobcreation'),
        ),
        migrations.AddField(
            model_name='mcq_exam_result',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_mcq_exam_template_id_result', to='company.template_creation'),
        ),
        migrations.AddField(
            model_name='mcq_exam',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_mcq_exam', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mcq_exam',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_mcq_exam', to='company.company'),
        ),
        migrations.AddField(
            model_name='mcq_exam',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_mcq_exam_job_id', to='company.jobcreation'),
        ),
        migrations.AddField(
            model_name='mcq_exam',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_mcq_question', to='company.mcq_question'),
        ),
        migrations.AddField(
            model_name='mcq_exam',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_mcq_exam_template_id', to='company.template_creation'),
        ),
        migrations.AddField(
            model_name='jcrratio',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_jcr_ratio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jcrratio',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_jcrratio_company_jcr_id', to='company.company'),
        ),
        migrations.AddField(
            model_name='jcrratio',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_jcrratio_job_id', to='company.jobcreation'),
        ),
        migrations.AddField(
            model_name='jcrratio',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_jcrratio_template_id', to='company.template_creation'),
        ),
        migrations.AddField(
            model_name='jcrfill',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_jcr_apply', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jcrfill',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_company_jcr_id', to='company.company'),
        ),
        migrations.AddField(
            model_name='jcrfill',
            name='jcr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_jcr_id', to='company.jcr'),
        ),
        migrations.AddField(
            model_name='jcrfill',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_job_id', to='company.jobcreation'),
        ),
        migrations.AddField(
            model_name='jcrfill',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_template_id', to='company.template_creation'),
        ),
        migrations.AddField(
            model_name='image_exam_result',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_image_exam_result', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image_exam_result',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_image_exam_result', to='company.company'),
        ),
        migrations.AddField(
            model_name='image_exam_result',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_image_exam_job_id_result', to='company.jobcreation'),
        ),
        migrations.AddField(
            model_name='image_exam_result',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_image_exam_template_id_result', to='company.template_creation'),
        ),
        migrations.AddField(
            model_name='image_exam',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_image_exam', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image_exam',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_image_exam', to='company.company'),
        ),
        migrations.AddField(
            model_name='image_exam',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_image_exam_job_id', to='company.jobcreation'),
        ),
        migrations.AddField(
            model_name='image_exam',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_image_question', to='company.imagequestion'),
        ),
        migrations.AddField(
            model_name='image_exam',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_image_exam_template_id', to='company.template_creation'),
        ),
        migrations.AddField(
            model_name='gap',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_gap_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gap',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_gap_profile_id', to='candidate.profile'),
        ),
        migrations.AddField(
            model_name='forgotpassword',
            name='candidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_forgot_password', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fitscore',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_FitScore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fitscore',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_FitScore_job_id', to='company.jobcreation'),
        ),
        migrations.AddField(
            model_name='examtimestatus',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_time_status_candidate_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examtimestatus',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_exam_time_status_job_id', to='company.jobcreation'),
        ),
        migrations.AddField(
            model_name='examtimestatus',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_time_status_template_id', to='company.template_creation'),
        ),
        migrations.AddField(
            model_name='descriptive_exam_result',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_Descriptive_exam_result', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='descriptive_exam_result',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_Descriptive_exam_result', to='company.company'),
        ),
        migrations.AddField(
            model_name='descriptive_exam_result',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_Descriptive_exam_job_id_result', to='company.jobcreation'),
        ),
        migrations.AddField(
            model_name='descriptive_exam_result',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_Descriptive_exam_template_id_result', to='company.template_creation'),
        ),
        migrations.AddField(
            model_name='descriptive_exam',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_Descriptive_exam', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='descriptive_exam',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_Descriptive_exam', to='company.company'),
        ),
        migrations.AddField(
            model_name='descriptive_exam',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_Descriptive_exam_job_id', to='company.jobcreation'),
        ),
        migrations.AddField(
            model_name='descriptive_exam',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_Descriptive_question', to='company.descriptive'),
        ),
        migrations.AddField(
            model_name='descriptive_exam',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_Descriptive_exam_template_id', to='company.template_creation'),
        ),
        migrations.AddField(
            model_name='company_data_request',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_candidate_hide_field_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company_data_request',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_hide_field_id', to='company.company'),
        ),
        migrations.AddField(
            model_name='company_data_request',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile_hide_field_id', to='candidate.profile'),
        ),
        migrations.AddField(
            model_name='codingscorecardfill',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_scorecard', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codingscorecardfill',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scorecard_company_id', to='company.company'),
        ),
        migrations.AddField(
            model_name='codingscorecardfill',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard_job_id', to='company.jobcreation'),
        ),
        migrations.AddField(
            model_name='codingscorecardfill',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scorecard_template_id', to='company.template_creation'),
        ),
        migrations.AddField(
            model_name='codingscorecardfill',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_user_scorecard_assessment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codingfrontendexamfill',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='front_end_exam_candidate_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codingfrontendexamfill',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='front_end_exam_company_id', to='company.company'),
        ),
        migrations.AddField(
            model_name='codingfrontendexamfill',
            name='exam_question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_frontend_exam_que_id', to='company.codingexamquestions'),
        ),
        migrations.AddField(
            model_name='codingfrontendexamfill',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_frontend_exam_job_id', to='company.jobcreation'),
        ),
        migrations.AddField(
            model_name='codingfrontendexamfill',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='front_end_exam_template_id', to='company.template_creation'),
        ),
        migrations.AddField(
            model_name='codingfrontendexamfill',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coding_front_end_assessment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codingbackendexamfill',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_end_exam_candidate_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codingbackendexamfill',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_end_exam_company_id', to='company.company'),
        ),
        migrations.AddField(
            model_name='codingbackendexamfill',
            name='exam_question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_backend_exam_que_id', to='company.codingexamquestions'),
        ),
        migrations.AddField(
            model_name='codingbackendexamfill',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_backend_exam_job_id', to='company.jobcreation'),
        ),
        migrations.AddField(
            model_name='codingbackendexamfill',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_end_exam_template_id', to='company.template_creation'),
        ),
        migrations.AddField(
            model_name='codingbackendexamfill',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coding_backend_assessment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coding_exam_result',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_coding_exam_result', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coding_exam_result',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_coding_exam_result', to='company.company'),
        ),
        migrations.AddField(
            model_name='coding_exam_result',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_coding_exam_result_job_id', to='company.jobcreation'),
        ),
        migrations.AddField(
            model_name='coding_exam_result',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_coding_exam_template_id_result', to='company.template_creation'),
        ),
        migrations.AddField(
            model_name='city',
            name='state_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_id', to='candidate.state'),
        ),
        migrations.AddField(
            model_name='candidatesummary',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_summary_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatesummary',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatesummary_profile_id', to='candidate.profile'),
        ),
        migrations.AddField(
            model_name='candidatesocialnetwork',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_network', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatesocialnetwork',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatesocial_profile_id', to='candidate.profile'),
        ),
        migrations.AddField(
            model_name='candidateskillusermap',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skill_user_map', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateskillusermap',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidateskill_profile_id', to='candidate.profile'),
        ),
        migrations.AddField(
            model_name='candidateskillusermap',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skill_user_map', to='candidate.skill'),
        ),
        migrations.AddField(
            model_name='candidateseo',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_seo_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatereference',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_reference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatereference',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatereference_profile_id', to='candidate.profile'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_city', to='candidate.city'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_country', to='candidate.country'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_gender', to='candidate.gender'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='marital_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_martial_status', to='candidate.maritaltype'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='notice_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_notice_period', to='candidate.noticeperiod'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidateprofile_profile_id', to='candidate.profile'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_state', to='candidate.state'),
        ),
        migrations.AddField(
            model_name='candidateportfolio',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_portfolio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateportfolio',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidateportfolio_profile_id', to='candidate.profile'),
        ),
        migrations.AddField(
            model_name='candidateotherfield',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_other_fields', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateotherfield',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidateother_profile_id', to='candidate.profile'),
        ),
        migrations.AddField(
            model_name='candidatelanguage',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_language', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatelanguage',
            name='fluency_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_fluency_id', to='candidate.fluency'),
        ),
        migrations.AddField(
            model_name='candidatelanguage',
            name='language_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_language_id', to='candidate.languages'),
        ),
        migrations.AddField(
            model_name='candidatelanguage',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatelanguage_profile_id', to='candidate.profile'),
        ),
        migrations.AddField(
            model_name='candidatejobpreferenceother',
            name='candidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_other_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatejobpreference',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_job_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatehobbies',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_hobby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatehobbies',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatehobby_profile_id', to='candidate.profile'),
        ),
        migrations.AddField(
            model_name='candidateexperience',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_experience', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateexperience',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_company_experience', to='candidate.company'),
        ),
        migrations.AddField(
            model_name='candidateexperience',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidateexperience_profile_id', to='candidate.profile'),
        ),
        migrations.AddField(
            model_name='candidateexpdocuments',
            name='candidate_exp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_exp_doc', to='candidate.candidateexperience'),
        ),
        migrations.AddField(
            model_name='candidateexpdocuments',
            name='candidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_exp_doc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateexpdocuments',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile_id', to='candidate.profile'),
        ),
        migrations.AddField(
            model_name='candidateeducation',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateeducation',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_degree', to='candidate.degree'),
        ),
        migrations.AddField(
            model_name='candidateeducation',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidateeducation_profile_id', to='candidate.profile'),
        ),
        migrations.AddField(
            model_name='candidateeducation',
            name='university_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_university', to='candidate.universityboard'),
        ),
        migrations.AddField(
            model_name='candidatecounter',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_counter_fields_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatecounter',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_counter_fields_id', to='candidate.profile'),
        ),
        migrations.AddField(
            model_name='candidatecertificationattachment',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_certificate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatecertificationattachment',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatecertification_profile_id', to='candidate.profile'),
        ),
        migrations.AddField(
            model_name='candidateaward',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_award', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateaward',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidateaward_profile_id', to='candidate.profile'),
        ),
        migrations.AddField(
            model_name='candidate_job_apply_detail',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_job_apply', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate_job_apply_detail',
            name='current_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_job_apply_detail_current_city', to='candidate.city'),
        ),
        migrations.AddField(
            model_name='candidate_job_apply_detail',
            name='notice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_job_apply_detail_applyjob_notice_period', to='candidate.noticeperiod'),
        ),
        migrations.AddField(
            model_name='candidate_job_apply_detail',
            name='prefered_city',
            field=models.ManyToManyField(null=True, related_name='candidate_job_apply_detail_prefered_city', to='candidate.City'),
        ),
        migrations.AddField(
            model_name='candidate_job_apply_detail',
            name='skills',
            field=models.ManyToManyField(null=True, related_name='candidate_job_apply_detail_skill_id', to='candidate.Skill'),
        ),
        migrations.AddField(
            model_name='candidate_job_apply_detail',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_job_apply_detail_source', to='candidate.source'),
        ),
        migrations.AddField(
            model_name='candidate_job_apply_detail',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='candidate_job_apply_detail_tags_id', to='candidate.Tags'),
        ),
        migrations.AddField(
            model_name='candidate_hide_fields',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_hide_field_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate_hide_fields',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_hide_field_id', to='candidate.profile'),
        ),
        migrations.AddField(
            model_name='basicdetail',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_BasicDetail_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basicdetail',
            name='notice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BasicDetail_applyjob_notice_period', to='candidate.noticeperiod'),
        ),
        migrations.AddField(
            model_name='basicdetail',
            name='prefered_city',
            field=models.ManyToManyField(null=True, related_name='BasicDetail_current_city', to='candidate.City'),
        ),
        migrations.AddField(
            model_name='basicdetail',
            name='skills',
            field=models.ManyToManyField(null=True, related_name='BasicDetail_skill_id', to='candidate.Skill'),
        ),
        migrations.AddField(
            model_name='audioexamquestionattemptunit',
            name='audio_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_exam_question_attempt_unit_audio_question', to='company.audioexamquestionunit'),
        ),
        migrations.AddField(
            model_name='audioexamattempt',
            name='audio_question_attempts',
            field=models.ManyToManyField(related_name='audio_exam_attempt_answers', to='candidate.AudioExamQuestionAttemptUnit'),
        ),
        migrations.AddField(
            model_name='audioexamattempt',
            name='audio_question_paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_exam_attempt_audio_question_paper', to='company.audioquestionpaper'),
        ),
        migrations.AddField(
            model_name='audioexamattempt',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_exam_attempt_candidate_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audioexamattempt',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_exam_attempt_company_id', to='company.company'),
        ),
        migrations.AddField(
            model_name='audioexamattempt',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_exam_attempt_job_id', to='company.jobcreation'),
        ),
    ]
