# Generated by Django 3.1 on 2022-03-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_remove_candidate_job_apply_detail_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage_list',
            name='display_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
