# Generated by Django 3.1 on 2022-03-31 10:16

import candidate.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0037_customresult_customscorecardresult'),
        ('candidate', '0005_stage_list_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency_PreRequisitesFill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisites_data', models.CharField(max_length=2000, null=True)),
                ('prerequisites_pdf', models.FileField(max_length=500, null=True, upload_to=candidate.models.agencyprerequisites_document_path_handler)),
                ('result', models.BooleanField(default=False)),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_candidate_PreRequisites_company_jcr_id', to='agency.agency')),
                ('candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_candidate_PreRequisites_ratio', to=settings.AUTH_USER_MODEL)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_candidate_PreRequisites_job_id', to='agency.jobcreation')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_candidate_PreRequisites_template_id', to='agency.template_creation')),
            ],
        ),
    ]
