# Generated by Django 3.1 on 2022-04-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_agency_image_exam_agency_image_exam_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidatesocialnetwork',
            name='network_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidatesummary',
            name='summary',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
