# Generated by Django 3.1 on 2022-04-06 13:15

import candidate.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0037_customresult_customscorecardresult'),
        ('candidate', '0012_agencydescriptive_exam_agencydescriptive_exam_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyAudioExamQuestionAttemptUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.FileField(default='dummy_attempt.webp', null=True, upload_to='audio_exam_recordings')),
                ('obtain_marks', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('audio_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_audio_exam_question_attempt_unit_audio_question', to='agency.audioexamquestionunit')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyAudioExamAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_pdf', models.FileField(max_length=500, null=True, upload_to=candidate.models.Agencyaudio_document_path_handler)),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_exam_attempt_agency_id', to='agency.agency')),
                ('audio_question_attempts', models.ManyToManyField(related_name='agency_audio_exam_attempt_answers', to='candidate.AudioExamQuestionAttemptUnit')),
                ('audio_question_paper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_audio_exam_attempt_audio_question_paper', to='agency.audioquestionpaper')),
                ('candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_audio_exam_attempt_candidate_id', to=settings.AUTH_USER_MODEL)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_audio_exam_attempt_job_id', to='agency.jobcreation')),
            ],
        ),
    ]
