# Generated by Django 3.1 on 2022-04-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_agencyaudioexamattempt_agencyaudioexamquestionattemptunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyaudioexamattempt',
            name='audio_question_attempts',
            field=models.ManyToManyField(related_name='agency_audio_exam_attempt_answers', to='candidate.AgencyAudioExamQuestionAttemptUnit'),
        ),
    ]
