# Generated by Django 3.1 on 2022-04-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_agencycoding_exam_result_agencycodingbackendexamfill_agencycodingfrontendexamfill_agencycodingscorec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_job_apply_detail',
            name='candidate_custom_id',
        ),
        migrations.RemoveField(
            model_name='candidate_job_apply_detail',
            name='secure_resume',
        ),
        migrations.RemoveField(
            model_name='candidate_job_apply_detail',
            name='secure_resume_file',
        ),
    ]
