# Generated by Django 3.1 on 2022-05-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0017_auto_20220511_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taststatus',
            name='status',
        ),
        migrations.AddField(
            model_name='codingapisubjects',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
