# Generated by Django 3.1 on 2022-05-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0018_auto_20220511_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
