# Generated by Django 3.1 on 2022-05-12 05:09

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0019_preority'),
    ]

    operations = [
        migrations.AddField(
            model_name='taststatus',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
