# Generated by Django 3.1 on 2022-05-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0021_remove_taststatus_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preority',
            new_name='Priority',
        ),
    ]
