# Generated by Django 3.1 on 2022-05-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0022_auto_20220512_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='current_salary',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
