# Generated by Django 3.1 on 2022-03-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220316_2055'),
    ]

   
