# Generated by Django 3.1 on 2022-05-03 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220317_0824'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VarifyCandidateEmail',
            new_name='VerifyCandidateEmail',
        ),
    ]
