# Generated by Django 3.1 on 2022-03-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20220304_0615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='comapny_id',
            new_name='company',
        ),
    ]
