# Generated by Django 3.1 on 2022-03-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20220304_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalcandidatebasicdetails',
            name='withdraw_by_Candidate',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
