# Generated by Django 3.1 on 2022-03-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_internalcandidatebasicdetails_withdraw_by_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatejobstagesstatus',
            name='reject_by_candidate',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
