# Generated by Django 3.1 on 2022-03-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_candidatejobstagesstatus_reject_by_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedcandidate',
            name='submit_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
