# Generated by Django 3.1 on 2022-03-21 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_remove_candidate_job_apply_detail_tags'),
        ('company', '0007_appliedcandidate_submit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcreation',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_status_id', to='candidate.jobstatus'),
        ),
    ]
