# Generated by Django 3.1 on 2022-03-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20220321_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatejobstagesstatus',
            name='custom_stage_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
