# Generated by Django 3.1 on 2022-04-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20220329_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
