# Generated by Django 3.1 on 2022-05-02 06:12

import company.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0016_auto_20220409_1033'),
        ('agency', '0047_auto_20220430_1324'),
        ('company', '0014_appliedcandidatebasicdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=10, null=True)),
                ('applied', models.BooleanField(default=False)),
                ('withdraw', models.BooleanField(default=False)),
                ('candidate_custom_id', models.CharField(max_length=10, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('resume', models.FileField(max_length=500, null=True, upload_to=company.models.resume_path_handler)),
                ('secure_resume', models.BooleanField(default=False, null=True)),
                ('secure_resume_file', models.FileField(max_length=500, null=True, upload_to=company.models.resume_path_handler)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('ctc', models.CharField(max_length=100, null=True)),
                ('expectedctc', models.CharField(max_length=100, null=True)),
                ('total_exper', models.CharField(max_length=100, null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='', verbose_name='DailySubmission_pf_pic_company')),
                ('create_at', models.DateTimeField(auto_now_add=True, max_length=200)),
                ('update_at', models.DateTimeField(max_length=200, null=True)),
                ('varify', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(null=True, related_name='DailySubmission_categories_id_company', to='company.CandidateCategories')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_submission_AssociateJob_company', to='company.company')),
                ('company_job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_daily_submission_job_id_company', to='company.jobcreation')),
                ('current_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DailySubmission_current_city_company', to='candidate.city')),
                ('internal_candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_submissionJob_id_company', to='agency.internalcandidatebasicdetail')),
                ('internal_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_submissionuser_company', to='company.employee')),
                ('notice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DailySubmission_applyjob_notice_period_company', to='candidate.noticeperiod')),
                ('prefered_city', models.ManyToManyField(null=True, related_name='DailySubmission_prefered_city_company', to='candidate.City')),
                ('skills', models.ManyToManyField(null=True, related_name='DailySubmission_skill_id_company', to='candidate.Skill')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DailySubmission_source_company', to='candidate.source')),
                ('tags', models.ManyToManyField(null=True, related_name='DailySubmission_tags_id_company', to='company.Tags')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_submissionAssociateJob_user_company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
