# Generated by Django 3.1 on 2022-05-02 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0047_auto_20220430_1324'),
        ('company', '0016_auto_20220502_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysubmission',
            name='internal_user_agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_submissionuser_company', to='agency.internaluserprofile'),
        ),
    ]
