# Generated by Django 3.1 on 2022-05-11 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0020_auto_20220503_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField()),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_id_TaskCategories', to='company.company')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user_id_TaskCategories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
