# Generated by Django 3.1 on 2022-05-12 05:11

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_taskcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcategories',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
