# Generated by Django 3.1 on 2022-05-13 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0022_auto_20220512_0947'),
        ('company', '0022_taskcategories_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskManagment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('create_at', models.DateTimeField(auto_now_add=True, max_length=200)),
                ('update_at', models.DateTimeField(max_length=200, null=True)),
                ('Assignee', models.ManyToManyField(related_name='Assignee_TaskManagment', to='company.Employee')),
                ('applied_candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_candidate_TaskManagment', to=settings.AUTH_USER_MODEL)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_TaskManagment', to='company.taskcategories')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_id_TaskManagment', to='company.company')),
                ('internal_candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_TaskManagment', to='company.internalcandidatebasicdetails')),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_TaskManagment', to='company.jobcreation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_TaskManagment', to='company.employee')),
                ('priority_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Priority_TaskManagment', to='candidate.priority')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_TaskManagment', to='candidate.taststatus')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user_id_TaskManagment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
