# Generated by Django 3.1 on 2022-05-13 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_taskmanagment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmanagment',
            old_name='Assignee',
            new_name='assignee',
        ),
    ]
